"""
Django settings for cms project.

Generated by 'django-admin startproject' using Django 6.1.

For more information on this file, see
https://docs.djangoproject.com/en/6.1/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/6.1/ref/settings/
"""

# Build paths inside the project like this: BASE_DIR / 'subdir'.
import os
from pathlib import Path

import dj_database_url
from dotenv import load_dotenv

PROJECT_DIR = Path(__file__).resolve().parent.parent
BASE_DIR = PROJECT_DIR.parent

load_dotenv(BASE_DIR / ".env")


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/6.1/howto/deployment/checklist/


# Application definition

INSTALLED_APPS = [
    "home",
    "search",
    # wadminoride ships Wagtail admin template overrides — it must sit
    # above wagtail.admin so Django's app-dirs template loader finds
    # its versions first.
    "wadminoride",
    "grapple",
    "graphene_django",
    "wagtail_headless_preview",
    "wagtail.contrib.forms",
    "wagtail.contrib.redirects",
    "wagtail.embeds",
    "wagtail.sites",
    "wagtail.users",
    "wagtail.snippets",
    "wagtail.documents",
    "wagtail.images",
    "wagtail.search",
    "wagtail.admin",
    "wagtail",
    "modelcluster",
    "taggit",
    "django_filters",
    "django.contrib.admin",
    "django.contrib.auth",
    "django.contrib.contenttypes",
    "django.contrib.postgres",
    "django.contrib.sessions",
    "django.contrib.messages",
    "django.contrib.staticfiles",
]

MIDDLEWARE = [
    "django.middleware.security.SecurityMiddleware",
    "whitenoise.middleware.WhiteNoiseMiddleware",
    "django.contrib.sessions.middleware.SessionMiddleware",
    "django.middleware.common.CommonMiddleware",
    "django.middleware.csrf.CsrfViewMiddleware",
    "django.contrib.auth.middleware.AuthenticationMiddleware",
    "django.contrib.messages.middleware.MessageMiddleware",
    "django.middleware.clickjacking.XFrameOptionsMiddleware",
    "wagtail.contrib.redirects.middleware.RedirectMiddleware",
]

ROOT_URLCONF = "core.urls"

TEMPLATES = [
    {
        "BACKEND": "django.template.backends.django.DjangoTemplates",
        "DIRS": [
            PROJECT_DIR / "templates",
        ],
        "APP_DIRS": True,
        "OPTIONS": {
            "context_processors": [
                "django.template.context_processors.debug",
                "django.template.context_processors.request",
                "django.contrib.auth.context_processors.auth",
                "django.contrib.messages.context_processors.messages",
                "wadminoride.context_processors.public_urls",
            ],
        },
    },
]

WSGI_APPLICATION = "core.wsgi.application"


# Database
# https://docs.djangoproject.com/en/6.1/ref/settings/#databases
#
# dj_database_url.config()'s `default=` only kicks in when the env
# var is missing entirely — an explicitly empty DATABASE_URL parses
# to django.db.backends.dummy and crashes on the first query. Read
# the raw env value ourselves so unset AND empty both fall through
# to the SQLite fallback.
_DATABASE_URL = os.environ.get("DATABASE_URL") or f"sqlite:///{BASE_DIR / 'db.sqlite3'}"
DATABASES = {
    "default": dj_database_url.parse(_DATABASE_URL, conn_max_age=600),
}


# Password validation
# https://docs.djangoproject.com/en/6.1/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        "NAME": "django.contrib.auth.password_validation.UserAttributeSimilarityValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.MinimumLengthValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.CommonPasswordValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.NumericPasswordValidator",
    },
]


# Internationalization
# https://docs.djangoproject.com/en/6.1/topics/i18n/

LANGUAGE_CODE = "en-us"

TIME_ZONE = "UTC"

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/6.1/howto/static-files/

STATICFILES_FINDERS = [
    "django.contrib.staticfiles.finders.FileSystemFinder",
    "django.contrib.staticfiles.finders.AppDirectoriesFinder",
]

STATICFILES_DIRS = [
    PROJECT_DIR / "static",
]

STATIC_ROOT = BASE_DIR / "static"
STATIC_URL = "/static/"

MEDIA_ROOT = BASE_DIR / "media"
MEDIA_URL = "/media/"

# Storage backends.
#
# Static files: always served via WhiteNoise (middleware is above), so
# the storage backend uses WhiteNoise's compressed variant everywhere.
# Production layers a manifest on top (see production.py) for
# cache-busting; dev keeps the non-manifest form so `runserver` works
# without a preceding `collectstatic`.
#
# Media (`default`): S3 when AWS_STORAGE_BUCKET_NAME is set to a
# non-empty value; local filesystem otherwise. Credentials come from
# the standard boto3 chain (env vars, instance profile, task role) —
# nothing sensitive is checked in here. Endpoint / region / custom
# domain overrides let the same block target S3-compatible services
# (R2, MinIO, Spaces) or a CDN.
STORAGES = {
    "default": {
        "BACKEND": "django.core.files.storage.FileSystemStorage",
    },
    "staticfiles": {
        "BACKEND": "whitenoise.storage.CompressedStaticFilesStorage",
    },
}

# GCS wins over S3 when both are set — this project runs on GCP, so
# the native backend is the expected one; S3 stays as a fallback for
# other deployments. Cloud Run's default service account authenticates
# to GCS via Application Default Credentials, so no keys need to be
# stored — just grant the SA `roles/storage.objectAdmin` on the bucket.
GS_BUCKET_NAME = os.environ.get("GS_BUCKET_NAME") or None
AWS_STORAGE_BUCKET_NAME = os.environ.get("AWS_STORAGE_BUCKET_NAME") or None

if GS_BUCKET_NAME:
    gs_options = {
        "bucket_name": GS_BUCKET_NAME,
        # Same-name uploads get a numeric suffix rather than overwriting —
        # a rendition regenerated at the same size is a new object.
        "file_overwrite": False,
        # Uniform bucket-level access is the recommended GCS default; the
        # backend should not attempt per-object ACLs against a uniform
        # bucket (it would 400).
        "default_acl": None,
        # Return plain https://storage.googleapis.com/<bucket>/<key> URLs
        # for a publicly readable bucket. Set GS_QUERYSTRING_AUTH=true if
        # the bucket is private and needs signed URLs.
        "querystring_auth": os.environ.get(
            "GS_QUERYSTRING_AUTH", "false"
        ).lower() == "true",
    }
    if project_id := os.environ.get("GS_PROJECT_ID"):
        gs_options["project_id"] = project_id
    if custom_endpoint := os.environ.get("GS_CUSTOM_ENDPOINT"):
        gs_options["custom_endpoint"] = custom_endpoint
    STORAGES["default"] = {
        "BACKEND": "storages.backends.gcloud.GoogleCloudStorage",
        "OPTIONS": gs_options,
    }
elif AWS_STORAGE_BUCKET_NAME:
    s3_options = {
        "bucket_name": AWS_STORAGE_BUCKET_NAME,
        "file_overwrite": False,
        "default_acl": None,
        "querystring_auth": os.environ.get(
            "AWS_S3_QUERYSTRING_AUTH", "false"
        ).lower() == "true",
    }
    if region := os.environ.get("AWS_S3_REGION_NAME"):
        s3_options["region_name"] = region
    if endpoint := os.environ.get("AWS_S3_ENDPOINT_URL"):
        s3_options["endpoint_url"] = endpoint
    if custom_domain := os.environ.get("AWS_S3_CUSTOM_DOMAIN"):
        s3_options["custom_domain"] = custom_domain
    STORAGES["default"] = {
        "BACKEND": "storages.backends.s3.S3Storage",
        "OPTIONS": s3_options,
    }

# Django sets a maximum of 1000 fields per form by default, but particularly complex page models
# can exceed this limit within Wagtail's page editor.
DATA_UPLOAD_MAX_NUMBER_FIELDS = 10_000


# Wagtail settings

WAGTAIL_SITE_NAME = "cms"

# Grapple / GraphQL
GRAPHENE = {
    "SCHEMA": "grapple.schema.schema",
}
GRAPPLE = {
    "APPS": ["home"],
    "RICH_TEXT_FORMAT": "html",
    "EXPOSE_GRAPHIQL": True,
}

# Search
# https://docs.wagtail.org/en/stable/topics/search/backends.html
WAGTAILSEARCH_BACKENDS = {
    "default": {
        "BACKEND": "wagtail.search.backends.database",
    }
}

# Base URL to use when referring to full URLs within the Wagtail admin backend -
# e.g. in notification emails, and for absolute image/document URLs in
# GraphQL responses (no request context). Don't include '/admin' or a
# trailing slash.
WAGTAILADMIN_BASE_URL = os.environ.get(
    "WAGTAILADMIN_BASE_URL", "http://localhost:8000"
)

# Public base URL of the Next.js frontend. Used both by the headless
# preview client and by the admin login page's branding link.
SERVE_BASE_URL = os.environ.get("SERVE_BASE_URL", "http://localhost:3000")

# Wagtail Headless Preview — sends the "preview" button in the admin to
# the Next.js /api/preview route with a token, which flips draftMode on
# and forwards to the real page URL.
#
# The CLIENT_URLS template interpolates `{SITE_ROOT_URL}` from the
# Wagtail Site record's hostname/port, which is the CMS itself (e.g.
# localhost:80 in dev) — not the frontend. That produces a broken
# preview URL like http://localhost/api/preview. Hardcoding the
# frontend base from SERVE_BASE_URL instead avoids the need to keep
# the Wagtail Site's hostname/port in sync with the frontend host, and
# keeps the same env var driving both the preview URL and the serve()
# redirect.
WAGTAIL_HEADLESS_PREVIEW = {
    "CLIENT_URLS": {
        "default": f"{SERVE_BASE_URL}/api/preview",
    },
    "SERVE_BASE_URL": SERVE_BASE_URL,
    "REDIRECT_ON_PREVIEW": True,
    "ENFORCE_TRAILING_SLASH": True,
}

# Allowed file extensions for documents in the document library.
# This can be omitted to allow all files, but note that this may present a security risk
# if untrusted users are allowed to upload files -
# see https://docs.wagtail.org/en/stable/advanced_topics/deploying.html#user-uploaded-files
# Video formats are included so editors can upload hero-slide videos
# through the document library (used by HeroItemBlock's video field).
WAGTAILDOCS_EXTENSIONS = [
    'csv', 'docx', 'key', 'odt', 'pdf', 'pptx', 'rtf', 'txt', 'xlsx', 'zip',
    'mp4', 'webm', 'mov',
]

# Maximum upload size for documents and images in bytes. Both default
# to 10 MB in Wagtail — bumped to 30 MB to allow hero videos and
# high-resolution image sources. 30 (rather than 50) so we stay
# under Cloud Run's 32 MiB HTTP/1 request-body cap; anything larger
# would 413 at the edge before reaching Django. If genuinely large
# uploads become common, switch to browser-direct signed-URL uploads
# to GCS (bypasses Cloud Run's cap entirely).
WAGTAILDOCS_MAX_UPLOAD_SIZE = 30 * 1024 * 1024  # 30 MB
WAGTAILIMAGES_MAX_UPLOAD_SIZE = 30 * 1024 * 1024  # 30 MB
