# Generated by Django 6.1 on 2026-09-01 13:48

import wagtail.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_homepage_hero'),
    ]

    operations = [
        migrations.AlterField(
            model_name='homepage',
            name='hero',
            field=wagtail.fields.StreamField([('item', 8)], blank=True, block_lookup={0: ('wagtail.blocks.CharBlock', (), {'help_text': 'The big headline on the slide.', 'max_length': 200, 'required': True}), 1: ('wagtail.blocks.TextBlock', (), {'help_text': 'Supporting sentence beneath the headline.', 'max_length': 500, 'required': False}), 2: ('wagtail.blocks.CharBlock', (), {'help_text': 'Primary button label (short — 1–3 words).', 'max_length': 50, 'required': True}), 3: ('wagtail.blocks.PageChooserBlock', (), {'help_text': 'Page the primary button links to.', 'required': True}), 4: ('wagtail.blocks.CharBlock', (), {'help_text': 'Secondary button label. Leave blank to hide.', 'max_length': 50, 'required': False}), 5: ('wagtail.blocks.PageChooserBlock', (), {'help_text': 'Page the secondary button links to (required if label is set).', 'required': False}), 6: ('wagtail.images.blocks.ImageChooserBlock', (), {'help_text': 'Background image. Leave blank if using video.', 'required': False}), 7: ('wagtail.documents.blocks.DocumentChooserBlock', (), {'help_text': 'Background video (mp4/webm/mov). Uploaded to the document library. If both image and video are set, video wins.', 'required': False}), 8: ('wagtail.blocks.StructBlock', [[('main_text', 0), ('sub_text', 1), ('primary_button_text', 2), ('primary_button_page', 3), ('secondary_button_text', 4), ('secondary_button_page', 5), ('image', 6), ('video', 7)]], {})}, help_text='Add 1–4 hero items. Reorder by dragging.'),
        ),
    ]
